# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#top_bar {\n"
"    background-color: #6E7271\n"
"}\n"
"\n"
"QWidget#frame_toggle {\n"
"    background-color:#ACAD94\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("QWidget#top_bar {\n"
"    Background-color: #384D48\n"
"}\n"
"\n"
"")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.top_bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("color: #D8D4D5;\n"
"border: 0px solid")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("QWidget#frame_left_menu {\n"
"    background-color:#384D48\n"
"}\n"
"\n"
"QWidget#frame_pages {\n"
"    background-color: #6E7271\n"
"}\n"
"")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(105, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Btn_Home = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Home.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Home.setStyleSheet("QPushButton {\n"
"    color: #D8D4D5;\n"
"    background-color: #ACAD94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #010000;\n"
"    background-color: #D8D4D5\n"
"}")
        self.Btn_Home.setObjectName("Btn_Home")
        self.verticalLayout_4.addWidget(self.Btn_Home)
        self.Btn_New = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_New.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_New.setStyleSheet("QPushButton {\n"
"    color: #D8D4D5;\n"
"    background-color: #ACAD94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #010000;\n"
"    background-color: #D8D4D5\n"
"}")
        self.Btn_New.setObjectName("Btn_New")
        self.verticalLayout_4.addWidget(self.Btn_New)
        self.Btn_Load = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Load.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Load.setStyleSheet("QPushButton {\n"
"    color: #D8D4D5;\n"
"    background-color: #ACAD94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #010000;\n"
"    background-color: #D8D4D5\n"
"}")
        self.Btn_Load.setObjectName("Btn_Load")
        self.verticalLayout_4.addWidget(self.Btn_Load)
        self.Btn_Vis = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Vis.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Vis.setStyleSheet("QPushButton {\n"
"    color: #D8D4D5;\n"
"    background-color: #ACAD94;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #010000;\n"
"    background-color: #D8D4D5\n"
"}")
        self.Btn_Vis.setObjectName("Btn_Vis")
        self.verticalLayout_4.addWidget(self.Btn_Vis)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Pages = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages.setObjectName("Pages")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.Pages.addWidget(self.page_home)
        self.page_load = QtWidgets.QWidget()
        self.page_load.setObjectName("page_load")
        self.Pages.addWidget(self.page_load)
        self.page_vis = QtWidgets.QWidget()
        self.page_vis.setObjectName("page_vis")
        self.Pages.addWidget(self.page_vis)
        self.page_new = QtWidgets.QWidget()
        self.page_new.setObjectName("page_new")
        self.Pages.addWidget(self.page_new)
        self.verticalLayout_5.addWidget(self.Pages)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setToolTip(_translate("MainWindow", "Toggle Menu"))
        self.Btn_Toggle.setText(_translate("MainWindow", "TOGGLE"))
        self.label.setText(_translate("MainWindow", "Substrate Database - NXPS"))
        self.Btn_Home.setToolTip(_translate("MainWindow", "Home view"))
        self.Btn_Home.setStatusTip(_translate("MainWindow", "hejhej"))
        self.Btn_Home.setText(_translate("MainWindow", "Home"))
        self.Btn_New.setToolTip(_translate("MainWindow", "New substrate"))
        self.Btn_New.setText(_translate("MainWindow", "New Substrate"))
        self.Btn_Load.setToolTip(_translate("MainWindow", "Load substrate"))
        self.Btn_Load.setText(_translate("MainWindow", "Load Substrate"))
        self.Btn_Vis.setToolTip(_translate("MainWindow", "Visualize"))
        self.Btn_Vis.setText(_translate("MainWindow", "Visualize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
